name: Test Actions for Discord Notifications

on:
  release:
    types: [ published ]

jobs:
  notify:
    name: Discord Notification
    runs-on: ubuntu-latest
    steps:
    - uses: Ilshidur/action-discord@0.0.2
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      with:
        args: 'The release [${{ ${{ github.event.tag_name }}](${{ github.event.url }}) of project ${{ github.repository }} has been released.'
